In [3]:
# bài tập về nhà
import numpy as np
mang = np.full((3, 3), 99)
print(mang)


[[99 99 99]
 [99 99 99]
 [99 99 99]]


In [ ]:
def print_mang(mang):
    for row in mang:
        print(["X" if cell == 1 else "O" if cell == 0 else " " for cell in row])
    print()

# Hàm xử lý trò chơi
def play_game():
    print("Trò chơi X và 0:")
    print("Người chơi X là 1 và người chơi O là 0.")
    print("Hãy nhập chỉ số (hàng, cột) để điền vào mảng.")

    # In mảng ban đầu
    print("Mảng ban đầu:")
    print_mang(mang)

    turn = 1  # Lượt chơi (1 = X, 0 = O)
    moves = 0  # Đếm số bước đi

    while True:
        try:
            # Nhập chỉ số từ người chơi
            move = input(f"Người chơi {'X' if turn == 1 else 'O'}, nhập cặp chỉ số (hàng, cột): ")
            row, col = map(int, move.strip("()").split(","))

            # Kiểm tra tính hợp lệ của chỉ số
            if row < 0 or row >= 3 or col < 0 or col >= 3:
                print("Vị trí không hợp lệ, vui lòng nhập lại!")
                continue

            # Kiểm tra nếu người chơi 0 nhập (0,0)
            if turn == 0 and (row, col) == (0, 0):
                print("Người chơi O không được chọn (0, 0). Vui lòng nhập lại!")
                continue

            # Kiểm tra nếu ô đã được điền
            if mang[row, col] != 99:
                print("Ô đã được điền, vui lòng nhập lại!")
                continue

            # Điền giá trị vào mảng
            mang[row, col] = turn
            moves += 1  # Tăng số lượt chơi

            # In mảng sau khi điền
            print_mang(mang)

            # Kiểm tra nếu có người thắng hoặc đã điền đủ
            if check_winner(mang, turn):
                print(f"Người chơi {'X' if turn == 1 else 'O'} thắng!")
                break
            elif moves == 9:
                print("Trò chơi hòa!")
                break

            # Đổi lượt
            turn = 1 - turn
        except Exception as e:
            print("Lỗi nhập liệu, vui lòng nhập lại theo định dạng (hàng, cột)!")

# Hàm kiểm tra người thắng
def check_winner(mang, player):
    # Kiểm tra hàng
    for row in mang:
        if np.all(row == player):
            return True
    # Kiểm tra cột
    for col in mang.T:
        if np.all(col == player):
            return True
    # Kiểm tra đường chéo
    if np.all(np.diag(mang) == player) or np.all(np.diag(np.fliplr(mang)) == player):
        return True
    return False

# Chạy trò chơi
play_game()




Trò chơi X và 0:
Người chơi X là 1 và người chơi O là 0.
Hãy nhập chỉ số (hàng, cột) để điền vào mảng.
Mảng ban đầu:
[' ', ' ', ' ']
[' ', ' ', ' ']
[' ', ' ', ' ']

Người chơi X, nhập cặp chỉ số (hàng, cột): 2,3
Vị trí không hợp lệ, vui lòng nhập lại!
