In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8])

In [ ]:
x[2] #lấy số 3 trong bảng

3

In [ ]:
# lấy từ 1 đến 3
x[0:3]

array([1, 2, 3])

In [ ]:
#lấy 3 đến 8
x[2:8]


array([3, 4, 5, 6, 7, 8])

In [ ]:
# lấy 7 và 8
x[6:8]

array([7, 8])

In [ ]:
# lấy phần tử index 2 và 4
x[2], x[4]

(3, 5)

In [ ]:
data =[(1,2),(3,4),(5,6)]
mang = np.array(data)
print(mang)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
mang[0,1]# lấy số 2


2

In [ ]:
# lấy 3 4 5 6
mang[1:3] #hoặc[1:] và mang[(1,2),:] và mang[1:, :]

array([[3, 4],
       [5, 6]])

In [ ]:
# lấy 1 3 5
mang[:,0]

array([1, 3, 5])

In [ ]:
# lấy 1 và 5 theo fomat start :end:step
mang[::2,0]

array([1, 5])

In [ ]:
data =[(1,2,3,4),(5,6,7,8),(9,10,11,12),(13,14,15,16)]
mang = np.array(data)
print(mang)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
# lấy 2 6 10 14, lấy 7 11, lấy 4 7 10,lấy 16 15 14 13

In [ ]:
# lấy 2 6 10 14
mang[[0,1,2,3],[1,1,1,1]]# hoặc mang[0:1]

array([ 2,  6, 10, 14])

In [ ]:
# lấy 7 và 11
mang[1:3,2]

array([ 7, 11])

In [ ]:
# lấy 4 7 10
mang[[0,1,2],[3,2,1]]

array([ 4,  7, 10])

In [ ]:
# lấy 16 15 14 13
mang[-1,::-1] # hoặc x[3,::-1]


array([16, 15, 14, 13])

In [ ]:
#lấy 4 5 6 , lấy 2 5 lấy 3 4 lấy 9 6 3  bài tập 10 phút

In [ ]:
data =[(1,2,3,),(4,5,6),(7,8,9)]
mang = np.array(data)
print(mang)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# lấy 4 5 6
mang[1]

array([4, 5, 6])

In [ ]:
# lấy 2 5
mang[[0,1], [1,1]]

array([2, 5])

In [ ]:
# lấy 3 4
mang[[0,1],[2,0]]

array([3, 4])

In [ ]:
# lấy 9 6 3
mang[::-1,2]

array([9, 6, 3])

In [ ]:
data =(1,2,3,4,5,6,7,8,9,10)
mang = np.array(data)
print(mang)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
# in ra các phần tử chẵn
mang_chan = [num for num in mang if num % 2 == 0]
print(mang_chan)

[2, 4, 6, 8, 10]


In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(3)


array([0, 1, 2])

In [ ]:
np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
x = np.arange(3)
x.shape
x

array([0, 1, 2])

In [ ]:
np.ones((3,3)) + np.arange(3)


array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [ ]:
# BÀI TẬP KẾT NUMPY
# Tạo một máng numpy có kích thươc 158 x 5. Hãy tưởng tượng màng này chứa 150 mẫu về chiều cao, cân nặng, tuổi, lương, GPA của sinh viên VI # Chia màng bốn cột đầu tiên thành một biến có tên là X và cột cuối cùng thành y
# Chia X thành X_traán và X_test chứa 70% dữ liệu và chia y thành y_train và y_test, trong đó y_traán chứa 70% dữ liệu.
# Tạo 10 tập dữ liệu không chồng chéo của X_train
# bài tập về nhà 2 nhận xét imput outpus vầ numpy



In [ ]:
import numpy as np
x = np.random.rand(150, 5)


In [ ]:
train_size = int(0.7 * len(x))  # Chỉ số để chia 70% dữ liệu


In [ ]:
x_train = x[:train_size]  # 70% đầu tiên
x_test = x[train_size:]   # 30% còn lại


In [ ]:
# Chia X thành X_traán và X_test chứa 70% dữ liệu và chia y thành y_train và y_test, trong đó y_traán chứa 70% dữ liệu.
dataset_size = x.shape[0]
dataset_size

NameError: name 'x' is not defined

In [ ]:
train_size = int(0.7*dataset_size)
train_size

NameError: name 'dataset_size' is not defined

In [ ]:
x_train = x[:train_size]
x_test = x[train_size:]

x_train.shape,x_test.shape

NameError: name 'x' is not defined